# Generated by Django 5.1.4 on 2025-01-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchmate',
        ),
    ]
